---
- hosts: rpi
  become: yes
  gather_facts: true
  tasks:
    - name: Populate all service facts
      service_facts:

    - name: Print service domoticz.service
      debug:
        var: ansible_facts.services['domoticz.service']

    - include_role:
        name: wilmardo.domoticz
      vars:
        domoticz_download_dir: /home/domoticz # The directory where the downloaded files will be placed
        domoticz_url: https://releases.domoticz.com/releases/release/domoticz_linux_armv7l.tgz # The Domoticz download url
        domoticz_src: domoticz # The name of the untarred Domoticz directory
        domoticz_user: domoticz # The user which the Domoticz daemon runs as
        domoticz_group: domoticz # The group which the Domoticz daemon runs as
        #domoticz_port: 8888 # The port for Domoticz to run http (-www daemon option). For ports <1024 root privileges are required, better to setup a reverse proxy with for example Nginx
        domoticz_https: true # Enable/Disable https for Domoticz
        #domoticz_https_port: 443 # The port for Domoticz to run https (-sslwww daemon option). For ports <1024 root privileges are required, better to setup a reverse proxy with for example Nginx
        domoticz_ssl_cert: "{{ domoticz_download_dir }}/{{ domoticz_src }}/server_cert.pem" # Path to SSL certificate, if left default the server_cert.pem from Domoticz will be used (-sslcert daemon option)
        domoticz_zwave_support: true # Add support for ZWave
        zwave_version: master # The version of Open-ZWave to be installed (accepts same arguments as version parameter of git module)
        zwave_url: https://github.com/OpenZWave/open-zwave.git # The Open-ZWave git url
      when: "'domoticz.service' not in services"

    - name: Add domoticz user to dialout and tty group
      command: usermod -a -G dialout,tty domoticz

    - name: Enable logging for domoticz
      lineinfile: 
        dest: /lib/systemd/system/domoticz.service
        state: present 
        regexp: "^    ExecStart="
        line: "    ExecStart=/home/domoticz/domoticz/domoticz -www {{ domoticz_port }} -sslwww {{ domoticz_https_port }} -log /var/log/domoticz.log"
      notify:
        - Restart domoticz
        
    - name: Create domoticz log file
      file:
        path: /var/log/domoticz.log
        state: touch
        mode: '0777'

    - name: Copy logrotate for domoticz
      copy:
         src: logrotate-domoticz
         dest: /etc/logrotate.d/domoticz

    - name: Install Dashticz
      ansible.builtin.unarchive:
        src: https://github.com/Dashticz/dashticz/archive/refs/tags/v3.1.2.zip
        dest: /var/www/html/
        remote_src: yes

    - name: Delete dashticz directory
      file:
        state: absent
        path: /var/www/html/dashticz

    - name: Rename dashticz folder
      command: mv /var/www/html/dashticz-3.1.2 /var/www/html/dashticz

    - name: Set Dashticz configuration
      template:
        src: CONFIG.js.j2
        dest: /var/www/html/dashticz/custom/CONFIG.js
        owner: root
        group: root
        mode: 0644

    - name: Copy dashticz/index.html
      copy:
         src: dashticz/index.html
         dest: /var/www/html/dashticz

    - name: Copy dashticz/custom.css
      copy:
         src: dashticz/custom.css
         dest: /var/www/html/dashticz/custom

    - name: Install RPI monitoring
      ansible.builtin.git:
        repo: https://github.com/Xorfor/Domoticz-PiMonitor-Plugin
        dest: /home/domoticz/domoticz/plugins/PiMonitor
      notify:
        - Restart domoticz

    - name: Set permissions on PiMonitor
      file:
        path: /home/domoticz/domoticz/plugins/PiMonitor
        state: directory
        owner: domoticz
        group: domoticz
        recurse: yes

    - name: Install WLED plugin
      ansible.builtin.git:
        repo: https://github.com/frustreermeneer/domoticz-wled-plugin.git
        dest: /home/domoticz/domoticz/plugins/wled
      notify:
        - Restart domoticz

    - name: Set permissions on wled
      file:
        path: /home/domoticz/domoticz/plugins/wled
        state: directory
        owner: domoticz
        group: domoticz
        recurse: yes

  handlers:
    - name: Restart domoticz
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        enabled: yes
        name: domoticz.service

#################################### END #######################################